# Generated by Django 4.2.24 on 2025-09-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_about_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboraterequest',
            name='title',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
