# Generated by Django 4.2.24 on 2025-09-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_collaboraterequest_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaboraterequest',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
